### Remember to load plugin during PDB start (no 'hot-loading' of plugins so far..)

In [1]:
import pandas as pd
from lbs.localpdb import PDB
pdb = PDB(db_path='/home/db/pdb', common_filters=True, plugins=['ECOD'])

### Now you can load ECOD data...

In [2]:
pdb.load_ecod_data('/home/users/jludwiczak/ecod.latest.domains.txt')

### ... which is accessible like this

pdb.ecod

In [4]:
pdb.ecod.head()

,pdb_id,ecod_number,arch_name,x_name,h_name,t_name,f_name,ligand,pdb_range,seqid_range,x_id,h_id,t_id,f_id
ecod_domain_id,,,,,,,,,,,,,,
e3s8iA1,3s8i_A,1.1.1.3,beta barrels,cradle loop barrel,RIFT-related,acid protease,Asp_protease,"EDO,PO4,UNX",A:241-367,A:22-148,1,1,1,3
e2i1aA1,2i1a_A,1.1.1.3,beta barrels,cradle loop barrel,RIFT-related,acid protease,Asp_protease,NO_LIGANDS_4A,A:200-324,A:23-147,1,1,1,3
e2i1aB1,2i1a_B,1.1.1.3,beta barrels,cradle loop barrel,RIFT-related,acid protease,Asp_protease,NO_LIGANDS_4A,B:199-325,B:22-148,1,1,1,3
e2i1aC1,2i1a_C,1.1.1.3,beta barrels,cradle loop barrel,RIFT-related,acid protease,Asp_protease,NO_LIGANDS_4A,C:199-325,C:22-148,1,1,1,3
e2i1aD1,2i1a_D,1.1.1.3,beta barrels,cradle loop barrel,RIFT-related,acid protease,Asp_protease,NO_LIGANDS_4A,D:201-323,D:24-146,1,1,1,3

####  !!! By default only pdb_id's which are in pdb.chains are loaded to pdb.ecod (to match indexes between the two df's) - this is especially important if you first manipulate pdb.chains and use load_ecod_data() afterwards !!!

## Example of usage

#### Selecting some enzyme of interest:

In [5]:
df = pdb.ecod[pdb.ecod['t_name'] == 'Thymidylate synthase/dCMP hydroxymethylase']

In [6]:
df.head()

,pdb_id,ecod_number,arch_name,x_name,h_name,t_name,f_name,ligand,pdb_range,seqid_range,x_id,h_id,t_id,f_id
ecod_domain_id,,,,,,,,,,,,,,
e1bkpA1,1bkp_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,NO_LIGANDS_4A,A:2-279,A:1-278,266,1,1,1
e1b5eA1,1b5e_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,DCM,A:1-241,A:1-241,266,1,1,1
e3nrrA2,3nrr_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,"CL,D16,EDO,GOL,UMP",A:195-511,A:199-515,266,1,1,1
e4q0dE2,4q0d_E,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,"2XB,UFP",E:193-521,E:193-521,266,1,1,1
e4o7uB1,4o7u_B,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,"EDO,SO4,THF",B:1-315,B:1-315,266,1,1,1

#### Now select only those containing single ligand type

In [10]:
df = df[df['ligand'] == 'UMP']

In [11]:
df.head()

,pdb_id,ecod_number,arch_name,x_name,h_name,t_name,f_name,ligand,pdb_range,seqid_range,x_id,h_id,t_id,f_id
ecod_domain_id,,,,,,,,,,,,,,
e2g86A1,2g86_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,UMP,A:1-316,A:1-316,266,1,1,1
e2g89A1,2g89_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,UMP,A:1-316,A:1-316,266,1,1,1
e2g8aA1,2g8a_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,UMP,A:1-316,A:1-316,266,1,1,1
e2g8dA1,2g8d_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,UMP,A:1-316,A:1-316,266,1,1,1
e1jmfA1,1jmf_A,266.1.1.1,a+b two layers,NO_X_NAME,NO_H_NAME,Thymidylate synthase/dCMP hydroxymethylase,Thymidylat_synt,UMP,A:1-316,A:1-316,266,1,1,1

In [12]:
len(df), len(df['pdb_id'].unique())

(84, 84)

#### Merge with pdb.chains DF

In [28]:
df = pd.merge(pdb.chains.loc[df.pdb_id], df,  left_index=True, right_on='pdb_id')

#### Filter and sort by resolution

In [30]:
df = df[df['resolution'] <= 2.5].sort_values(by='resolution')

#### Get unique PDB structures (not chains)

In [34]:
df['pdb'] = df['pdb_id'].apply(lambda x: x.split('_')[0])

In [37]:
ids = df.groupby(by='pdb').idxmin().index.tolist()
pdb.structures.loc[ids]

,type,method,resolution,fn_struct,fn_bio
1bid,prot,diffraction,2.20,/home/db/pdb/structures/bi/1bid.pdb,/home/db/pdb/biounits/bi/1bid.pdb1
1j3i,prot,diffraction,2.33,/home/db/pdb/structures/j3/1j3i.pdb,/home/db/pdb/biounits/j3/1j3i.pdb1
1j3j,prot,diffraction,2.30,/home/db/pdb/structures/j3/1j3j.pdb,/home/db/pdb/biounits/j3/1j3j.pdb1
1j3k,prot,diffraction,2.10,/home/db/pdb/structures/j3/1j3k.pdb,/home/db/pdb/biounits/j3/1j3k.pdb1
1jmf,prot,diffraction,2.50,/home/db/pdb/structures/jm/1jmf.pdb,/home/db/pdb/biounits/jm/1jmf.pdb1
1jmg,prot,diffraction,2.20,/home/db/pdb/structures/jm/1jmg.pdb,/home/db/pdb/biounits/jm/1jmg.pdb1
1jmh,prot,diffraction,2.50,/home/db/pdb/structures/jm/1jmh.pdb,/home/db/pdb/biounits/jm/1jmh.pdb1
1jmi,prot,diffraction,2.50,/home/db/pdb/structures/jm/1jmi.pdb,/home/db/pdb/biounits/jm/1jmi.pdb1
1njd,prot,diffraction,2.20,/home/db/pdb/structures/nj/1njd.pdb,/home/db/pdb/biounits/nj/1njd.pdb1
1tsx,prot,diffraction,2.50,/home/db/pdb/structures/ts/1tsx.pdb,/home/db/pdb/biounits/ts/1tsx.pdb1
1tsy,prot,diffraction,2.20,/home/db/pdb/structures/ts/1tsy.pdb,/home/db/pdb/biounits/ts/1tsy.pdb1
1vza,prot,diffraction,2.50,/home/db/pdb/structures/vz/1vza.pdb,/home/db/pdb/biounits/vz/1vza.pdb1
1vzb,prot,diffraction,2.50,/home/db/pdb/structures/vz/1vzb.pdb,/home/db/pdb/biounits/vz/1vzb.pdb1
2aaz,prot,diffraction,2.08,/home/db/pdb/structures/aa/2aaz.pdb,/home/db/pdb/biounits/aa/2aaz.pdb1
2g86,prot,diffraction,2.40,/home/db/pdb/structures/g8/2g86.pdb,/home/db/pdb/biounits/g8/2g86.pdb1
2g89,prot,diffraction,2.50,/home/db/pdb/structures/g8/2g89.pdb,/home/db/pdb/biounits/g8/2g89.pdb1
2g8a,prot,diffraction,2.40,/home/db/pdb/structures/g8/2g8a.pdb,/home/db/pdb/biounits/g8/2g8a.pdb1
2g8d,prot,diffraction,2.40,/home/db/pdb/structures/g8/2g8d.pdb,/home/db/pdb/biounits/g8/2g8d.pdb1
3qg2,prot,diffraction,2.30,/home/db/pdb/structures/qg/3qg2.pdb,/home/db/pdb/biounits/qg/3qg2.pdb1
3qgt,prot,diffraction,2.30,/home/db/pdb/structures/qg/3qgt.pdb,/home/db/pdb/biounits/qg/3qgt.pdb1
3um5,prot,diffraction,2.40,/home/db/pdb/structures/um/3um5.pdb,/home/db/pdb/biounits/um/3um5.pdb1
4dpd,prot,diffraction,2.50,/home/db/pdb/structures/dp/4dpd.pdb,/home/db/pdb/biounits/dp/4dpd.pdb1
4e5o,prot,diffraction,1.70,/home/db/pdb/structures/e5/4e5o.pdb,/home/db/pdb/biounits/e5/4e5o.pdb1
5h39,prot,diffraction,2.00,/home/db/pdb/structures/h3/5h39.pdb,/home/db/pdb/biounits/h3/5h39.pdb1
5x5d,prot,diffraction,2.00,/home/db/pdb/structures/x5/5x5d.pdb,/home/db/pdb/biounits/x5/5x5d.pdb1

## Another example

In [38]:
import pandas as pd
from lbs.localpdb import PDB
pdb = PDB(db_path='/home/db/pdb', common_filters=True, plugins=['ECOD'])

In [39]:
pdb.load_ecod_data('/home/users/jludwiczak/ecod.latest.domains.txt')

#### Get only Rossman-like

In [43]:
pdb.ecod = pdb.ecod[pdb.ecod['x_name'] == 'Rossmann-like']

In [48]:
len(pdb.ecod)

24046

In [52]:
pdb.ecod['has_SAM'] = pdb.ecod['ligand'].apply(lambda x: 'SAM' in str(x))
pdb.ecod = pdb.ecod[pdb.ecod['has_SAM'] == True]
del pdb.ecod['has_SAM']
len(pdb.ecod)

439

In [53]:
pdb.ecod.head()

,pdb_id,ecod_number,arch_name,x_name,h_name,t_name,f_name,ligand,pdb_range,seqid_range,x_id,h_id,t_id,f_id
ecod_domain_id,,,,,,,,,,,,,,
e5d4uA1,5d4u_A,2003.1.1.348,a/b three-layered sandwiches,Rossmann-like,Rossmann-related,NAD(P)-binding Rossmann-fold domains,DUF1188,"SAM,SO4",A:12-268,A:12-268,2003,1,1,348
e5d4uB1,5d4u_B,2003.1.1.348,a/b three-layered sandwiches,Rossmann-like,Rossmann-related,NAD(P)-binding Rossmann-fold domains,DUF1188,"SAM,SO4",B:12-268,B:12-268,2003,1,1,348
e5d4uC1,5d4u_C,2003.1.1.348,a/b three-layered sandwiches,Rossmann-like,Rossmann-related,NAD(P)-binding Rossmann-fold domains,DUF1188,"SAM,SO4",C:12-268,C:12-268,2003,1,1,348
e5d4uD1,5d4u_D,2003.1.1.348,a/b three-layered sandwiches,Rossmann-like,Rossmann-related,NAD(P)-binding Rossmann-fold domains,DUF1188,"SAM,SO4",D:12-268,D:12-268,2003,1,1,348
e3dmfA2,3dmf_A,2003.1.5,a/b three-layered sandwiches,Rossmann-like,Rossmann-related,S-adenosyl-L-methionine-dependent methyltransf...,F_UNCLASSIFIED,"SAM,SO4",A:3-195,A:3-195,2003,1,5,0

#### Collapse to single pdb_chain

In [72]:
len(pdb.ecod)

439

In [71]:
def group_func(x):
    data = {}
    for ecod_domain_id, _id, pdb_range, seqid_range in zip(x.index, x['ecod_number'], x['pdb_range'], x['seqid_range']):
        data[ecod_domain_id] = [_id, pdb_range, seqid_range]
    return data

In [74]:
pdb.ecod.groupby('pdb_id').apply(group_func).head()

pdb_id
1eiz_A    {'e1eizA1': ['2003.1.5.13', 'A:30-209', 'A:1-1...
1ej0_A    {'e1ej0A1': ['2003.1.5.13', 'A:30-209', 'A:1-1...
1fpq_A    {'e1fpqA3': ['2003.1.5.26', 'A:129-159,A:180-3...
1g60_A    {'e1g60A1': ['2003.1.5.52', 'A:1-256', 'A:1-25...
1g60_B    {'e1g60B1': ['2003.1.5.52', 'B:1-256', 'B:1-25...
dtype: object

In [75]:
len(pdb.ecod.groupby('pdb_id').apply(group_func))

432

#### Example of collapsed pdb_chain with 2 domains

In [81]:
for key, value in pdb.ecod.groupby('pdb_id').apply(group_func).iteritems():
    if len(value) > 1:
        print(key, value)
        break

2zul_A {'e2zulA1': ['2003.1.5', 'A:3-195', 'A:3-195'], 'e2zulA2': ['2003.1.5.86', 'A:196-374', 'A:196-374']}